<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Reviva.version.props" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateKSPAssemblyAttribute>true</GenerateKSPAssemblyAttribute>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="0.0.4" />
  </ItemGroup>
</Project>